-- Updates for production database schema (from local)
-- Generated by Antigravity on 2026-02-19

-- Missing Table: Log_Actividades
CREATE TABLE IF NOT EXISTS `Log_Actividades` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` int(11) NOT NULL,
  `accion` varchar(50) NOT NULL,
  `detalle` text DEFAULT NULL,
  `fecha` datetime DEFAULT current_timestamp(),
  `ip_address` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `usuario_id` (`usuario_id`),
  CONSTRAINT `log_actividades_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `Usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Missing Table: Mensajes
CREATE TABLE IF NOT EXISTS `Mensajes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `remitente_id` int(11) NOT NULL,
  `destinatario_id` int(11) DEFAULT NULL COMMENT 'NULL for global messages if needed, currently intended for specific users',
  `asunto` varchar(255) NOT NULL,
  `cuerpo` text NOT NULL,
  `leido` tinyint(1) DEFAULT 0,
  `fecha` datetime DEFAULT current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `remitente_id` (`remitente_id`),
  KEY `destinatario_id` (`destinatario_id`),
  CONSTRAINT `mensajes_ibfk_1` FOREIGN KEY (`remitente_id`) REFERENCES `Usuarios` (`id`),
  CONSTRAINT `mensajes_ibfk_2` FOREIGN KEY (`destinatario_id`) REFERENCES `Usuarios` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- New Columns (Found in Local, Missing in Production)
ALTER TABLE `Finanzas_Cuentas` ADD COLUMN `deleted_at` datetime DEFAULT NULL;
ALTER TABLE `Inscripciones` ADD COLUMN `deleted_at` datetime DEFAULT NULL;

ALTER TABLE `Usuarios` ADD COLUMN `matricula` varchar(20) DEFAULT NULL;
ALTER TABLE `Usuarios` ADD COLUMN `deleted_at` datetime DEFAULT NULL;

ALTER TABLE `finanzas_boletos` ADD COLUMN `deleted_at` datetime DEFAULT NULL;
ALTER TABLE `finanzas_cargos` ADD COLUMN `deleted_at` datetime DEFAULT NULL;
ALTER TABLE `finanzas_eventos` ADD COLUMN `deleted_at` datetime DEFAULT NULL;
